#web容器配置
server:
  port: 7659
  servlet:
    context-path: /lottery
    session:
      cookie:
        max-age: 604800
#mybatis配置
mybatis:
  type-aliases-package: com.superywd.lottery.manage.source
  mapper-locations: classpath:mapping/*.xml
#spring框架配置
spring:
  application:
    name: lottery
  jmx:
    default-domain: lottery
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/static/



