spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最小空闲连接数量
      minimum-idle: 5
      #空闲连接存活最大时间
      idle-timeout: 600000
      #最大连接数
      maximum-pool-size: 10
      #获取连接的自动提交行为
      auto-commit: true
      #连接最大生命周期
      max-lifetime: 1800000
      #连接的最大超时时间
      connection-timeout: 30000
      #测试连接
      connection-test-query: SELECT 1
    master:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://47.106.66.7/lottery?characterEncoding=utf8&autoReconnect=true&useAffectedRows=true
      username: root
      password: scanf
    slave1:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://47.106.66.7/lottery?characterEncoding=utf8&autoReconnect=true&useAffectedRows=true
      username: only_read
      password: scanf
    slave2:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://47.106.66.7/lottery?characterEncoding=utf8&autoReconnect=true&useAffectedRows=true
      username: only_read
      password: scanf
